//! Async thumbnail request command. Calls pfp_photos for the heavy work,
//! emits `thumbnail-ready` when done. The frontend never receives bytes via
//! IPC — it consumes them via the pfp-thumb:// URI scheme (Pitfall 2-B).
//!
//! Bounded concurrency (Pattern 4) via TauriAppState.thumb_semaphore.
//! Duplicate-request dedup (Pitfall 2-I) via TauriAppState.in_flight.

use std::path::PathBuf;

use serde::Serialize;
use tauri::{Emitter, Manager, State};

use crate::app_state::TauriAppState;
use crate::error::WireError;

#[derive(Debug, Clone, Serialize)]
#[serde(tag = "status", rename_all = "snake_case")]
pub enum RequestThumbnailAck {
    Ready,    // cache hit; webview can fetch pfp-thumb:// immediately
    InFlight, // already being generated by a previous request
    Queued,   // newly queued; thumbnail-ready event will fire
}

#[derive(Debug, Clone, Serialize)]
struct ThumbnailReadyPayload {
    id: String,
}

#[derive(Debug, Clone, Serialize)]
struct ThumbnailFailedPayload {
    id: String,
    /// Short, dev-facing reason. Frontend logs it; the row keeps the
    /// placeholder icon per UI-SPEC.
    reason: String,
}

#[tauri::command]
pub async fn request_thumbnail(
    state: State<'_, TauriAppState>,
    app: tauri::AppHandle,
    id: String,
) -> Result<RequestThumbnailAck, WireError> {
    // Resolve id → PathBuf.
    let path: PathBuf = {
        let map = state.thumbnail_id_map.lock().map_err(|e| WireError::Io {
            detail: format!("id_map lock: {e}"),
        })?;
        map.get(&id).cloned().ok_or_else(|| WireError::Photos {
            detail: format!("unknown photo id: {id}"),
        })?
    };

    let folder = path
        .parent()
        .ok_or_else(|| WireError::Photos {
            detail: format!("photo path has no parent: {}", path.display()),
        })?
        .to_path_buf();

    // Cache hit short-circuit.
    if pfp_photos::cache::cache_file(&folder, &id).exists() {
        return Ok(RequestThumbnailAck::Ready);
    }

    // Dedup.
    {
        let mut in_flight = state.in_flight.lock().map_err(|e| WireError::Io {
            detail: format!("in_flight lock: {e}"),
        })?;
        if in_flight.contains(&id) {
            return Ok(RequestThumbnailAck::InFlight);
        }
        in_flight.insert(id.clone());
    }

    // Spawn the decode work. Permit acquisition + blocking decode happen on the
    // tokio runtime; the original IPC future returns immediately with Queued.
    let semaphore = state.thumb_semaphore.clone();
    let folder_owned = folder.clone();
    let path_owned = path.clone();
    let id_for_task = id.clone();
    let app_for_task = app.clone();

    // We've already cloned everything we need. The spawned task re-resolves
    // TauriAppState from the AppHandle to update the in-flight set.
    tauri::async_runtime::spawn(async move {
        let _permit = match semaphore.acquire_owned().await {
            Ok(p) => p,
            Err(_) => {
                eprintln!("[request_thumbnail] semaphore closed");
                return;
            }
        };

        // Heavy CPU work goes onto a blocking thread.
        let id_for_blocking = id_for_task.clone();
        let folder_for_blocking = folder_owned.clone();
        let path_for_blocking = path_owned.clone();
        let bytes_result: Result<Vec<u8>, pfp_photos::error::PhotosError> =
            tokio::task::spawn_blocking(move || {
                let bytes = pfp_photos::thumbnail::decode_resize_encode(&path_for_blocking)?;
                pfp_photos::cache::write_atomic(&folder_for_blocking, &id_for_blocking, &bytes)?;
                Ok(bytes)
            })
            .await
            .unwrap_or_else(|join_err| {
                Err(pfp_photos::error::PhotosError::Decode(format!(
                    "thumbnail decode panicked: {join_err}"
                )))
            });

        // Always release the in_flight slot, regardless of success/failure.
        let task_state: tauri::State<'_, TauriAppState> = app_for_task.state();
        if let Ok(mut in_flight) = task_state.in_flight.lock() {
            in_flight.remove(&id_for_task);
        }

        match bytes_result {
            Ok(_) => {
                let _ = app_for_task.emit(
                    "thumbnail-ready",
                    ThumbnailReadyPayload {
                        id: id_for_task.clone(),
                    },
                );
            }
            Err(e) => {
                eprintln!("[request_thumbnail] decode failed for {id_for_task}: {e}");
                // WR-06: emit thumbnail-failed so the frontend can drop the
                // id from its `requested` set and let the IntersectionObserver
                // retry on next viewport entry. Without this event, a transient
                // failure (USB reconnect, quota recovery) would never re-attempt
                // for the lifetime of the folder load. The row still keeps the
                // placeholder per UI-SPEC -- the event only resets the dedup
                // bookkeeping, it does not change the visible row state.
                let _ = app_for_task.emit(
                    "thumbnail-failed",
                    ThumbnailFailedPayload {
                        id: id_for_task.clone(),
                        reason: e.to_string(),
                    },
                );
            }
        }
    });

    Ok(RequestThumbnailAck::Queued)
}
